[package]
name = "mimic_emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
plex = "0.3.1"
regex = "1.10"
thiserror = "1.0"

[features]
mips32_assembler = []
mips32_emulator = []
mips32 = ["mips32_assembler", "mips32_emulator"]

default = ["mips32"]
